const tmpUser = {
  userAgreement: false,
  bvn_data: {},
  userInfo: {
    id: '',
    status: '',
    dob: '',
    firstName: '',
    lastName: '',
    middleName: '',
    address: '',
    phone: {
      number: '',
      verfied: 'none',
    },
  },

  mobileInfo: {
    brand: '',
    model: '',
  },
  mobileEvaluation: {
    status: 'initial',
    appraisedValue: 0,
    price: 0,
    DisplayEvaluation: {
      status: 'initial',
      appraisedValue: 0,
      touch: [false, 0],
      dim: [false, 0],
      pixel: [false, 0],
      discolor: [false, 0],
      whiteSpot: [false, 0],
      proximity: [false, 0],
      rotation: [false, 0],
    },
    cameraEvaluation: {
      status: 'initial',
      appraisedValue: 0,
      frontCamera: [false, 0],
      backCamera: [false, 0],
      cameraFlash: [false, 0],
      cameraVideo: [false, 0],
    },
    connectivityEvaluation: {
      status: 'initial',
      appraisedValue: 0,
      wifi: [false, 0],
      bluetooth: [false, 0],
      mbdata: [false, 0],
      simCard: [false, 0],
      sdCard: [false, 0],
    },
    audioEvaluation: {
      status: 'initial',
      appraisedValue: 0,
      earPiece: [false, 0],
      headSet: [false, 0],
      loudSpeaker: [false, 0],
      microphone: [false, 0],
      vibration: [false, 0],
    },
    batteryEvaluation: {
      status: 'initial',
      appraisedValue: 0,
      charge: [false, 0],
      volumeButton: [false, 0],
      powerButton: [false, 0],
      fingerPrint: [false, 0],
      faceId: [false, 0],
    },
  },
  balance: {
    currentBalance: 0,
    borrowableAmount: 0,
    paymentDue: 0,
    dueDate: '',
    creditScore: 0,
    calandar: [],
  },
}
